name: Kubernetes CI

on:
  push:
    branches:
      - '*'
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python packages
        shell: bash
        run: |
          python -m pip install --upgrade pip setuptools wheel coverage
          python -m pip install -r python/conda-spec.txt

      - name: Start minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: none

      - name: Install kubernetes dependencies
        shell: bash
        run: |
          python -m pip install kubernetes
          kubectl get pods -A

      - name: Test with pytest
        shell: bash
        run: |
          export PYTHONPATH="$PYTHONPATH:$(pwd):$(pwd)/python"
          python python/setup.py build_ext -i
          export PYTEST_CONFIG_WITHOUT_COV="--log-level=DEBUG --timeout=1500 -W ignore::PendingDeprecationWarning"
          export PYTEST_CONFIG="$PYTEST_CONFIG_WITHOUT_COV --cov-config=python/setup.cfg --cov-report= --cov=python/xorbits/deploy"
          pytest $PYTEST_CONFIG -s python/xorbits/deploy/kubernetes
          coverage report
          coverage xml

      - name: Report coverage data
        shell: bash
        run: |
          bash <(curl -s https://codecov.io/bash)
